### ISSUE TITLE
Node stop not working as expected

### ISSUE THREAD

**Issue by hclivess** [bismuthfoundation/Bismuth#14]
When node is asked to stop half-way through digesting, it ends up triggering status every second (includes peer testing) before it finishes digesting the current block range (tested in RAM mode)

I'm almost certain the issue is here:
```
                for i in range(30):
                    # faster stop
                    if not self.node.IS_STOPPING:
                        time.sleep(1)
```
and it actually slows down the shutdown instead of making it quicker

**Comment by EggPool** [comment]
Unrelated to the faster stop snippet.

Fixed by
https://github.com/bismuthfoundation/Bismuth/commit/2fbb269a653940b79305b3d2dfb26f86c6b8c7c3
https://github.com/bismuthfoundation/Bismuth/commit/72b39541dd029142219b68f293c0e8faabe47e86
See related comments.

**Comment by hclivess** [comment]
Perfect, thanks
